echo Building...
REACT_APP_STAGE='prod' npm run build

echo Deploying...
aws s3 sync build/ s3://tiktok-manager-prod/

echo Invalidating CloudFront cache...
aws cloudfront create-invalidation --distribution-id E2VGTQ0M3R7IYH --paths /index.html --output text
