echo Building...
REACT_APP_STAGE='staging' npm run build

echo Deploying...
aws s3 sync build/ s3://tiktok-manager-internal/

echo Invalidating CloudFront cache...
aws cloudfront create-invalidation --distribution-id E2ZFYHAEC9G6VM --paths /index.html --output text
